### ISSUE TITLE
CoC suggestions

### ISSUE THREAD

**Issue by onealexharms** [selfconference/2015-planning#28]
I'd like to suggest two small changes.

current version:

> self.conference is dedicated to providing a harassment-free conference experience for everyone, regardless of gender,

suggested change:

> self.conference is dedicated to providing a **welcoming and** harassment-free conference experience for everyone, regardless of gender **(cis- or trans-)**,

Here's why. Before I gave an actual fuck about codes of conduct, I was at a conference that did some gender-based things that turned out to make me pretty uncomfortable. They also had disability access issues, though I'd have an easier time arguing about those, whether they wanted to be welcoming or not.

But the crux is this: I didn't know whether to bring  up my discomfort, because I couldn't tell whether they _intended_ to be welcoming to people like me. I didn't feel safe talking about the gender stuff, especially. (I was still feeling like it was my fault I couldn't perform gender correctly. Over that. ^__^) I figured they'd say "if you're so weird that you can't handle ___" that's your problem. This is why I think it's important to say that you're welcoming, and not just forbid harassment.

If the website is a public repo somewhere, mea culpa, I'll do this as a pull-request instead. Just point the way.

**Comment by crebma** [comment]
<3 Thanks for this feedback and back story! The CoC is updated. :)
